### ISSUE TITLE
Compilation with conda openalea.deploy

### ISSUE THREAD

**Issue by jbdurand** [openalea/StructureAnalysis#49]
It seems that StructureAnalysis cannot be compiled with the current conda version of openalea.deploy and openalea.sconsx found on channel conda-forge.

```
cd StructureAnalysis/tool && \
    python2.7 setup.py install
```
yields
```
Traceback (most recent call last):
 File "setup.py", line 9, in <module>
   from openalea.deploy.metainfo import read_metainfo
ImportError: No module named openalea.deploy.metainfo
```

How to update  metainfo.ini and setup.py so as to compile with the updated versions of openalea.deploy and openalea.sconsx ?

**Comment by pradal** [comment]
Outdated : Python 3 only
