### ISSUE TITLE
Merging versions of StructureAnalysis (SequenceAnalysis, StatTools)

### ISSUE THREAD

**Issue by jbdurand** [openalea/StructureAnalysis#51]
### Available / known versions of sequence_analysis:###

1) git@gricad-gitlab.univ-grenoble-alpes.fr:durandje/vplants.bak.git
2) git@gitlab.inria.fr:statify_public/jemr-ema.git (developed by Brice Olivier, PhD)
3) git@github.com:openalea/docker-stacks.git ->  https://github.com/openalea/StructureAnalysis.git -b new_python_api

Among 1) and 2), 2) is more recent and complete (information criteria, etc.).
It includes some improved graphical outputs (html). Some bugs were fixed, including in stat_tools/src/cpp/reestimation.hpp. Includes some new initialization algorithm for EM in hidden semi-Markov chains (HSMCs). Some spurious messages have to be deleted from stat_tools/src/cpp/discrete_mixture_algorithms.cpp. 2) does not contain aml though and compatibility with various AML versions was not tested.

Comparing 2) and 3), 3) has an up to date compilation framework (python-openalea.deploy and python-openalea.sconsx instead of installing OpenAlea from sources).
3) has updated comments, in English with extra formatting, updated variable type names (NOMINAL instead of SYMBOLIC), standardized inputs for functions (string instead of char*), probably in view of using AutoWIG.
`template <typename Type> void Reestimation<Type>::equilibrium_process_estimation(const Reestimation<Type> *length_bias_reestim , Distribution *dist , double imean) const`
may have to be merged, as well as html visualization of HSMCs in 2).

**Comment by thomasarsouze** [comment]
Done with 63a48ca9fd6d6fdc716aa0715afc7cdd735b4db8
