### ISSUE TITLE
Interfacing sequence_analysis with Python

### ISSUE THREAD

**Issue by thomasarsouze** [openalea/StructureAnalysis#56]
Currently, wrappers compilation is [commented in `stat_tool`](https://github.com/openalea/StructureAnalysis/blob/new_python_api/stat_tool/SConstruct#L50-L51) but works in `sequence_analysis`. Uncommenting the lines leads to a compilation issue. This suggests that C++ code diverges from associated wrappers implementation.

This possibilities are the following:
- debug the wrapping in `new_python_api` branch, sticking to python2.7
- directly creating a python3 version / interface either boost / autowig / pybind11

**Comment by pradal** [comment]
No. The wrappers have not been built and the C++ API have evolved...

**Comment by pradal** [comment]
I build the old wrappers and update slightly the code on my computer (Mac).
Push it in the branch

**Comment by pradal** [comment]
Done
